baseURL = 'https://gent-systems.com/'
languageCode = 'en-us'
title = 'Gent-Systems'
theme = 'ananke'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true

[params]
  author = "John Gentile"
  favicon = "img/GS_logo.svg"
  description = "Gent-Systems"
  site_logo = "img/Gent-systems_icon_white_64.png"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  recent_posts_number = 6

[[params.ananke_socials]]
name = "github"
url = "https://github.com/Gent-Systems"
label = "Gent-Systems GitHub"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/company/gent-systems"
label = "Gent-Systems LinkedIn"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

